const $ = s => document.querySelector(s);
const key = 'qinghe-school-v1';
const subjects = {chinese:'语文',math:'数学',english:'英语',physics:'物理',chemistry:'化学',biology:'生物',history:'历史',politics:'政治',geography:'地理'};
const npcs=[{id:'Li Qiang',name:'李强',initial:'强',role:'篮球场上的少年',color:'#e8dfcc',gift:'冰镇汽水',gain:5,cost:5},{id:'Su Ruoyun',name:'苏若云',initial:'云',role:'认真温柔的班长',color:'#e2e8d5',gift:'精装笔记本',gain:8,cost:20},{id:"Lin Wan'er",name:'林婉儿',initial:'婉',role:'怀抱吉他的女孩',color:'#eadfd8',gift:'进口画笔',gain:15,cost:35}];
const initial=()=>({version:1,week:1,round:1,legacy:0,perks:[],track:'all',attrs:{stamina:100,stress:0,money:100,action_points:4,chinese:60,math:60,english:60,physics:50,chemistry:50,biology:50,history:50,politics:50,geography:50},bonds:[0,0,0],locks:[false,false,false],events:[],logs:[{week:1,text:'新学期，你走进了青禾高中的校门。'}],tea:0,study:0,highStress:0,exam:null,graduated:false,earned:[],inventory:[]});
let state=initial(); let storageOK=true;
try{const data=JSON.parse(localStorage.getItem(key));if(data&&data.version===1&&data.attrs&&Array.isArray(data.bonds))state={...initial(),...data};}catch{storageOK=false;}
let page='home',toastTimer,letterTimer;
const nav=[['home','⌂','校园日常'],['study','▤','学业成长'],['friends','♧','同窗羁绊'],['weekend','♙','周末时光'],['exam','✎','考场风云'],['memories','▧','青春纪念册'],['legacy','↻','新的篇章']];
const events=[['军训的下马威',1,'烈日暴晒下的军姿，教官的哨声响彻操场。'],['第一次月考考场',8,'高中的第一次大考，试卷难度远超初中。'],['班委选举之争',16,'班主任宣布竞选班干部，苏若云向你投来鼓励的眼神。'],['晚自习停电事件',24,'教室骤然漆黑，四周一片欢呼，林婉儿偷偷递给你一块蛋糕。'],['期末暴雨冲刷',36,'淋雨回家的那一天，复习资料堆满了书桌。'],['命运的分水岭',40,'文理分科表发了下来，这是决定未来方向的时刻。'],['运动会接力赛',48,'交接棒的瞬间，你为李强拼尽全力地呐喊。'],['漫长的期中阴霾',58,'连续的错题让你自我怀疑，窗外的雨下个不停。'],['艺术节的后台',64,'林婉儿的吉他弦突然断了，你在后台寻找备用弦。'],['跨年夜的誓言',80,'零点钟声敲响，你们在天台许下未来的誓言。'],['百日誓师大会',90,'巨型横幅挂在教学楼前，呐喊声震耳欲聋。'],['篮球赛的危机',108,'李强在球场上受伤，你们一起面对青春的挫折。'],['模拟考涂卡错位',120,'距离交卷还有五分钟，你发现答题卡错位了。'],['撕书狂欢节',140,'最后一个晚自习结束，试纸雪花般从教学楼飘落。'],['终极决战：高考',156,'走进考场，验证三年汗水与宿命的最终时刻。']];
const achievementNames=['天台看客','算圣','一网情深','卷王之王','情感大师','涂卡惊魂','饮茶先啦','逆天改命','名落孙山','象牙塔顶'];
const achievementDesc=['累计经历 3 个高压力周','数学能力达到 150','网吧系统尚未接入','每周学习 15 次（当前行动制暂不可达）','三位同学羁绊均达到 60','涂卡剧情尚未接入','累计喝奶茶超过 20 杯','李强救赎剧情尚未接入','高考成绩低于 200','考试排名第 1'];
const grade=()=>state.week<40?'高一':state.week<90?'高二':'高三';
const bar=(value,max=100)=>`<div class="bar"><i style="width:${Math.max(0,Math.min(100,value/max*100))}%"></i></div>`;
const title=(name,sub='')=>`<div class="page-heading"><div><h1>${name}</h1><p class="sub">${sub}</p></div><div class="date-pill">☀ <b>${grade()} · 第 ${state.week} 周</b><span>|</span> ${state.attrs.action_points?'校园时光':'周末时光'}</div></div>`;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}$('#save-status').textContent=storageOK?'已自动保存 · 当前浏览器': '存储不可用 · 本次进度仅保留在页面';}
function log(text){state.logs.unshift({week:state.week,text});state.logs=state.logs.slice(0,80);}
function clamp(){for(const k of ['stamina','stress'])state.attrs[k]=Math.max(0,Math.min(100,state.attrs[k]));for(const k in subjects)state.attrs[k]=Math.max(0,Math.min(150,state.attrs[k]));}
function checkAchievements(){const a=state.attrs;const tests=[state.highStress>=3,a.math===150,false,state.study>=15,state.bonds.every(x=>x>=60),false,state.tea>20,false,state.graduated&&state.exam?.score<200,state.exam?.rank===1];tests.forEach((v,i)=>{if(v&&!state.earned.includes(i)){state.earned.push(i);log('解锁成就：'+achievementNames[i]);}});}
function commit(message){clamp();checkAchievements();persist();render();if(message)toast(message);}
function modal(html){$('#dialog-content').innerHTML=html;$('#dialog').showModal();}
function closeModal(){clearInterval(letterTimer);$('#dialog').close();}
function canAct(){if(state.graduated){toast('本周目已毕业，可以前往新的篇章。');return false;}if(state.attrs.action_points<=0){toast('本周行动已用完，去商业街逛逛，或进入下一周。');return false;}return true;}
const campus=`<svg viewBox="0 0 600 270" xmlns="http://www.w3.org/2000/svg" aria-label="午后阳光里的校园插画" role="img"><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="#e9eddf"/><stop offset="1" stop-color="#d9e2ca"/></linearGradient><pattern id="windows" width="35" height="35" patternUnits="userSpaceOnUse"><rect x="7" y="6" width="17" height="22" rx="1" fill="#899c88"/><path d="M15 6v22M7 16h17" stroke="#c7c8b0" stroke-width="2"/></pattern></defs><circle cx="465" cy="65" r="37" fill="#f8f2d8"/><path d="M0 219Q130 155 253 215T600 195V270H0" fill="#becda8"/><path d="M110 224L185 184 536 210 600 270H108Z" fill="#c6c9ad"/><g stroke="#aaa98a" stroke-width="2"><path d="M163 98H491V221H163Z" fill="#e4ddbd"/><path d="M150 93H506V104H150Z" fill="#b7b497"/><path d="M291 58H365V225H291Z" fill="#eae3c9"/><path d="M282 60L328 32 376 60Z" fill="#809480"/><path d="M283 60H376V68H283Z" fill="#c6bda0"/></g><path d="M178 116H279V209H178ZM381 116H481V209H381Z" fill="url(#windows)"/><path d="M163 151H290M366 151H491M163 186H290M366 186H491" stroke="#c4bd9f" stroke-width="4"/><circle cx="328" cy="89" r="15" fill="#f6f2df" stroke="#b5b594" stroke-width="3"/><path d="M328 80V89L336 92" fill="none" stroke="#7b8972" stroke-width="2"/><rect x="308" y="120" width="40" height="49" fill="#93a18a"/><path d="M328 120V169M308 144H348" stroke="#ddd8bc" stroke-width="4"/><path d="M307 223V198Q328 174 349 198V223" fill="#7c8e78"/><path d="M294 228H362M283 234H373" stroke="#b6b39a" stroke-width="5"/><path d="M311 238L270 270H414L344 239" fill="#dedac0"/><g fill="#93ab7f"><ellipse cx="138" cy="169" rx="33" ry="48"/><ellipse cx="520" cy="155" rx="31" ry="53"/><ellipse cx="565" cy="185" rx="32" ry="37"/></g><g fill="#a5b88d"><circle cx="110" cy="195" r="27"/><circle cx="155" cy="180" r="25"/><circle cx="510" cy="173" r="32"/></g><g stroke="#819374" stroke-width="4"><path d="M136 180V239M520 168V232M565 190V244"/></g><path d="M0 265Q115 211 227 261M428 270Q537 224 600 249" stroke="#a5b98b" stroke-width="28" fill="none"/><g stroke="#87977c" fill="none"><path d="M402 54q5-6 10 0q5-6 10 0M435 37q4-5 8 0q4-5 8 0"/></g><path d="M466 118V214" stroke="#899582" stroke-width="2"/><path d="M467 118h23l-5 8h-18" fill="#ba8d73"/><g fill="#e8eddd"></g></svg>`;
function stats(){const a=state.attrs;return `<div class="stats">${[['♡','体力',a.stamina,'/ 100','给自己充充电','stamina'],['◌','压力',a.stress,'/ 100',a.stress>60?'适当放松一下':'状态轻松','stress'],['▱','零花钱',a.money,'元','周末去逛逛','money'],['ϟ','本周行动',a.action_points,'/ 4','每一步都算数','action_points']].map(([ic,label,v,unit,hint,k])=>`<div class="stat"><div class="stat-top"><i>${ic}</i>${label}</div><strong>${v}</strong><small>${unit}</small><span class="hint">${hint}</span>${bar(v,k==='action_points'?4:k==='money'?300:100)}</div>`).join('')}</div>`;}
function subjectList(all=false){let keys=all?Object.keys(subjects):['chinese','math','english',...(state.track==='arts'?['history','politics','geography']:['physics','chemistry','biology'])];return keys.map(k=>`<div class="subject-row"><span>${subjects[k]}</span>${bar(state.attrs[k],150)}<small>${state.attrs[k]} / 150</small></div>`).join('');}
function journal(n=4){return state.logs.slice(0,n).map(l=>`<div class="journal-entry"><time>第 ${l.week} 周</time><span>${l.text}</span></div>`).join('');}
function home(){const e=events.filter(e=>e[1]<=state.week).at(-1);return title('新的一天，慢慢发光。','学习、相遇、成长。今天的故事，由你来写。')+`<section class="hero"><div class="hero-copy"><div class="eyebrow">CHAPTER ${String(grade()==='高一'?1:grade()==='高二'?2:3).padStart(2,'0')} / 那些闪闪发光的日子</div><h2>白云漫过晴空，<br>小河流向青春的下一章。</h2><p>沿着校园旁的小河，把心事交给风，把期待写进蓝天。</p><div class="chapter"><span>${grade()} · ${state.week<40?'初见':state.week<90?'成长':'奔赴'}</span>距离毕业，还有 ${156-state.week} 周 <span style="background:none">→</span></div></div>${campus}</section>`+stats()+`<div class="grid"><div><section class="panel"><div class="section-title"><h2>✧ &nbsp; 此刻，做点什么 <span class="tag">${state.attrs.action_points} 次行动可用</span></h2><span class="status-badge">自由安排你的时光</span></div><article class="event"><div class="event-label">校园记事 / MAIN STORY</div><h3>${e[0]}</h3><p>${e[2]}</p><div class="event-bottom"><span>♧ &nbsp; 第 ${e[1]} 周的青春片段</span><button class="text-btn" data-action="event">${state.events.includes(e[1])?'重温故事':'翻开这一页'} &nbsp; →</button></div></article><div class="actions"><button class="action" data-action="study"><div class="action-icon">▤</div><h3>埋头学习</h3><p>今天也离梦想近一点。</p><div class="action-bottom"><span>ϟ 1 行动 · 体力 −5</span><span>↗</span></div></button><button class="action" data-action="rest"><div class="action-icon">☕</div><h3>偷闲片刻</h3><p>让紧绷的弦松一松。</p><div class="action-bottom"><span>ϟ 1 行动 · 压力 −15</span><span>↗</span></div></button><button class="action" data-go="friends"><div class="action-icon">♧</div><h3>找同学聊聊</h3><p>有些心事，想说给你听。</p><div class="action-bottom"><span>去同窗羁绊送一份心意</span><span>↗</span></div></button></div><div class="day-end"><p>不必每时每刻都奔跑，偶尔停下来也很好。</p><button class="primary" data-action="next">${state.week===156?'迎接高考':'结束本周'} &nbsp; →</button></div></section><section class="journal"><div class="section-title"><h2>时光小记</h2><button class="link" data-go="memories">全部记录 ↗</button></div>${journal()}</section></div><div class="right-column"><section class="panel"><div class="section-title"><h2>学业晴雨表</h2><button class="link" data-go="study">查看全部 ↗</button></div><p class="sub">一点点积累，也是一种了不起。</p>${subjectList()}<div class="track"><span class="tag">${state.track==='all'?'尚未分科':state.track==='science'?'理科方向':'文科方向'}</span><span class="tag">单科能力上限 150</span></div></section><section class="panel subjects" style="margin-top:0"><div class="section-title"><h2>那些身边的人</h2><button class="link" data-go="friends">→</button></div>${npcs.map((n,i)=>`<div class="friend-row"><div class="avatar" style="background:${n.color}">${n.initial}</div><div class="friend-info"><strong>${n.name}</strong><small>${state.bonds[i]<40?'初识':'相知'}</small>${bar(state.bonds[i])}</div><span class="bond">♡ ${state.bonds[i]}</span></div>`).join('')}</section><div class="note"><h3>☀ &nbsp; 写给今天的你</h3><p>成绩是青春的一部分，不是全部。<br>记得抬头看看晚霞，也记得照顾好自己。</p></div></div></div>`;}
function studyPage(){return title('把梦想，写进每一道题。','学业成长 / 长路漫漫，日有所进。')+stats()+`<div class="grid"><section class="panel"><div class="section-title"><h2>我的学科</h2><span class="tag">能力值 · 非实际考试成绩</span></div>${subjectList(true)}<button class="primary" data-action="study">开始一次专注学习 →</button></section><section class="panel"><h2>找到你的方向</h2><p class="page-intro">第 40 周起可选择文理方向。语文、数学、英语是共同的基础。</p><div class="choices"><button data-track="science" ${state.week<40?'disabled':''}>理科方向 <small>物理 / 化学 / 生物</small></button><button data-track="arts" ${state.week<40?'disabled':''}>文科方向 <small>历史 / 政治 / 地理</small></button></div><div class="note"><h3>学习小贴士</h3><p>压力超过 60 会降低学习效率；体力充足时，学习效果更好。每次学习消耗 1 次行动、5 点体力，增加 8 点压力。</p></div></section></div>`;}
function friendsPage(){return title('很高兴，同窗的你在。','同窗羁绊 / 青春里不只有分数，还有彼此。')+`<p class="page-intro">送出喜欢的礼物，拉近一点距离。羁绊达到 40、80 时进入阶段锁；完整契约剧情在原后端中尚未实现。</p><div class="cards">${npcs.map((n,i)=>`<article class="feature-card"><div class="avatar" style="background:${n.color}">${n.initial}</div><h3>${n.name}</h3><p>${n.role}</p><div class="section-title"><span class="status-badge">${state.locks[i]?'阶段锁 · 等待后续剧情':'正在慢慢了解彼此'}</span><span class="bond">♡ ${state.bonds[i]} / 100</span></div>${bar(state.bonds[i])}<p>喜欢的礼物：${n.gift}<br>价格 ¥${n.cost} · 羁绊 +${n.gain}<br>本地体验：每份礼物消耗 1 次行动。</p><button class="primary" data-gift="${i}" ${state.locks[i]||state.graduated?'disabled':''}>送一份心意 →</button></article>`).join('')}</div><section class="panel wide"><h3>书包里的收藏</h3><p class="sub">${state.inventory.length?state.inventory.join(' · '):'书包里还没有收藏，周末去旧书摊看看吧。'}</p></section>`;}
const shops=[['stationery','▤','转角文具店','一本新的辅导书，藏着下一次进步。','¥30 · 数学 +3'],['milktea','☕','放学后奶茶铺','热珍珠奶茶，是给努力的你的小奖励。','¥15 · 压力 −20 · 体力 +5'],['old_bookstall','▧','巷口旧书摊','偶遇绝版考题，也可能是一本闲书。','¥8 · 随机收获'],['part_time_job','▱','街角便利店','试着做半天大人，赚一点零花钱。','收入 ¥80 · 体力 −15 · 压力 +10']];
function weekendPage(){const open=state.attrs.action_points===0&&!state.graduated;return title('周末，把时间还给自己。','周末商业街 / 生活的另一面，也值得认真体验。')+stats()+`<p class="page-intro">${open?'周末已到，去喜欢的小店逛逛吧。':'完成本周 4 次校园行动后开放商业街。'}本地体验中，购买礼物和商店消费直接使用零花钱。</p><div class="cards">${shops.map(s=>`<article class="feature-card"><div class="big-icon">${s[1]}</div><h3>${s[2]}</h3><p>${s[3]}</p><p>${s[4]}</p><button class="primary" data-shop="${s[0]}" ${!open?'disabled':''}>${s[0]==='part_time_job'?'去打工':'进店看看'} →</button></article>`).join('')}</div><div class="day-end"><p>逛完了吗？新的故事正在下一周等你。</p><button class="primary" data-action="next">${state.week===156?'迎接高考':'进入下一周'} →</button></div>`;}
function examPage(){return title('笔尖落下，答案由你书写。','考场风云 / 每一种策略，都是一次选择。')+`<div class="grid"><form class="panel" id="exam-form"><div class="section-title"><h2>${state.week===156?'最终高考':'模拟考试'}</h2><span class="tag">三步考场策略</span></div><p class="page-intro">${state.graduated?'本周目已毕业，可查看最后一次成绩。':'本地模拟原后端的策略算法；实际分数包含随机波动。模拟考每次消耗 1 次行动。'}</p><label class="field">01 / 作文如何落笔？<select name="essay"><option value="steady">稳扎稳打 · 稳定增加 10 分</option><option value="risky">另辟蹊径 · 可能 +30，也可能 −20</option></select></label><label class="field">02 / 面对数学压轴题<select name="math"><option value="safe">先拿稳基础分 · 不额外冒险</option><option value="force">挑战压轴 · 数学能力大于 100 时 +25，否则 −15</option></select></label><label class="field">03 / 最后五分钟<select name="check"><option value="careful">仔细检查 · 增加 5 分</option><option value="quick">提前交卷 · 15% 概率失误扣 40 分</option></select></label><button class="primary" type="submit" ${state.graduated?'disabled':''}>${state.week===156?'交上高考答卷':'交卷，看看这次的成长'} →</button></form><section class="panel"><h2>最近一次成绩</h2>${state.exam?`<div class="result"><strong>${state.exam.score}</strong> / 750<p>模拟年级排名 ${state.exam.rank} / 1000</p></div><p class="page-intro">第 ${state.exam.week} 周 · ${state.graduated?'高考':'模拟考试'}<br>原后端成绩模型以语数英能力总和为基础计算，其他学科暂未计入。</p>`:'<p class="page-intro">还没有考试记录。选好你的策略，准备第一次落笔。</p>'}<div class="note"><p>一次考试无法定义你。<br>把每次练习，变成下一次的底气。</p></div></section></div>`;}
function memoriesPage(){return title('那些日子，后来都有了名字。','青春纪念册 / 收集微小成就，记住每一次成长。')+`<div class="section-title"><h2>成长勋章</h2><span class="tag">${state.earned.length} / 10 已解锁</span></div><div class="cards">${achievementNames.map((n,i)=>`<article class="feature-card achievement ${state.earned.includes(i)?'earned':''}"><span class="big-icon">${state.earned.includes(i)?'✧':'◇'}</span><h3>${n}</h3><p>${achievementDesc[i]}</p><span class="status-badge">${state.earned.includes(i)?'已点亮':'尚未解锁'}</span></article>`).join('')}</div><section class="panel wide"><div class="section-title"><h2>毕业季 · 给未来的信</h2><button class="primary" data-action="letter">${state.graduated?'打开毕业信':'预览毕业信'} →</button></div><p class="sub">${state.graduated?ending():'第 156 周完成高考后，按成绩与最高羁绊生成结局。当前可预览逐字呈现的纪念信。'}</p></section><section class="panel wide"><h2>故事目录</h2><div class="timeline">${events.map(e=>`<article><small>第 ${e[1]} 周 ${state.events.includes(e[1])?'· 已珍藏':state.week>=e[1]?'· 时光经过':'· 尚未抵达'}</small><h3>${e[0]}</h3><p>${state.week>=e[1]?e[2]:'把这一页，留给未来的你。'}</p></article>`).join('')}</div></section><section class="panel wide"><h2>我的时光小记</h2>${journal(80)}</section>`;}
function legacyPage(){return title('再相逢，仍是少年。','新的篇章 / 带着上一段青春的礼物，重新出发。')+`<div class="grid"><form class="panel" id="legacy-form"><h2>选择你的天资</h2><p class="page-intro">毕业后结算遗产点：高考分数 ÷ 10 向下取整 + 成就数 × 10 + 满羁绊人数 × 20。开启新周目会重置当前进度。</p>${[['过目不忘',50,'学习基础收益提高 20%'],['家境优渥',40,'初始零花钱提升至 300 元'],['大心脏',30,'原后端已定义天资，但效果尚未实现']].map(p=>`<label class="perk"><input type="checkbox" name="perk" value="${p[0]}" data-cost="${p[1]}" ${p[0]==='大心脏'?'disabled':''}><span>${p[0]}<p class="sub">${p[2]}</p></span><small>${p[1]} 点</small></label>`).join('')}<p class="page-intro" id="perk-total">已选天资合计：0 点</p><button class="primary" ${!state.graduated?'disabled':''}>带着回忆，开始新周目 →</button></form><section class="panel"><span class="status-badge">我的青春遗产</span><div class="result"><strong>${state.legacy}</strong> 点</div><p>当前是第 ${state.round} 周目。</p><p class="page-intro">${state.graduated?'这一段青春已经完成，新的故事正等待开始。':'先认真过好这一段青春。完成高考后，即可开启新的篇章。'}</p><p class="sub">本周目天资：${state.perks.join('、')||'平凡，也有无限可能'}</p></section></div>`;}
function render(){page=location.hash.slice(1)||'home';if(!nav.some(n=>n[0]===page))page='home';$('#nav').innerHTML=nav.map(n=>`<a href="#${n[0]}" class="${page===n[0]?'active':''}" ${page===n[0]?'aria-current="page"':''}><span class="icon">${n[1]}</span>${n[2]}${n[0]==='home'?'<span class="nav-end">↗</span>':''}</a>`).join('');$('#crumb').textContent=nav.find(n=>n[0]===page)[2];$('.semester').innerHTML=`我的高中 · 第 ${state.round} 周目<span>把平凡的日子，写成自己的故事。</span>`;$('#main').innerHTML=({home,study:studyPage,friends:friendsPage,weekend:weekendPage,exam:examPage,memories:memoriesPage,legacy:legacyPage})[page]();}
function chooseStudy(){if(!canAct())return;modal(`<h2>让专注，有一个方向。</h2><p>选择今天要学习的学科。体力 −5，压力 +8，行动 −1。</p><div class="choices">${Object.entries(subjects).map(([k,v])=>`<button data-subject="${k}">${v}<small>当前 ${state.attrs[k]} / 150 →</small></button>`).join('')}</div>`);}
function study(k){if(!canAct())return;const a=state.attrs;const gain=Math.max(0,Math.round(3*(state.perks.includes('过目不忘')?1.2:1)*(1-Math.max(0,a.stress-60)/100)*(Math.min(100,a.stamina+20)/120)));const actual=Math.min(gain,150-a[k]);a[k]+=actual;a.stamina-=5;a.stress+=8;a.action_points--;state.study++;closeModal();log(`专注学习${subjects[k]}，能力提升 ${actual} 点。`);commit(`${subjects[k]} +${actual} · 努力的痕迹，悄悄留下。`);}
function rest(){if(!canAct())return;state.attrs.stamina+=20;state.attrs.stress-=15;state.attrs.action_points--;log('在树荫下休息了一会儿，重新找回自己的节奏。');commit('体力 +20，压力 −15。慢下来，也很好。');}
function nextWeek(){if(state.graduated){location.hash='legacy';return;}if(state.week===156){location.hash='exam';return;}if(state.attrs.action_points>0){modal(`<h2>为本周画上句号？</h2><p>你还有 ${state.attrs.action_points} 次行动未使用。进入下一周后，行动恢复至 4 次，体力恢复 15 点，剩余行动不会累积。</p><button class="primary" data-action="confirm-next">结束本周，继续向前 →</button>`);}else advance();}
function advance(){closeModal();if(state.attrs.stress>80)state.highStress++;state.week++;state.attrs.action_points=4;state.attrs.stamina+=15;state.study=0;log('新的星期开始了，又有一些值得期待的事。');commit('第 '+state.week+' 周，你好。');}
function gift(i){if(!canAct()||state.locks[i])return;const n=npcs[i];if(state.attrs.money<n.cost)return toast('零花钱不足，周末可以去便利店打工。');state.attrs.money-=n.cost;state.attrs.action_points--;const before=state.bonds[i];let after=Math.min(100,before+n.gain);for(const limit of [40,80])if(before<limit&&after>=limit){after=limit;state.locks[i]=true;break;}state.bonds[i]=after;log(`送给${n.name}一份${n.gift}，羁绊增加 ${after-before}。`);commit(state.locks[i]?'羁绊达到阶段锁，后续契约剧情尚未接入。':`${n.name}收下了礼物。羁绊 +${after-before}`);}
function shop(id){if(state.attrs.action_points!==0||state.graduated)return;const a=state.attrs;const cost={stationery:30,milktea:15,old_bookstall:8,part_time_job:0}[id];if(a.money<cost)return toast('零花钱不够了，试着去便利店打工吧。');if(id==='part_time_job'&&a.stamina<15)return toast('体力不足 15，先喝杯奶茶或下周再来。');a.money-=cost;let message='';if(id==='stationery'){a.math+=3;state.inventory.push('高分辅导书');message='带回一本高分辅导书，数学 +3。';}if(id==='milktea'){a.stress-=20;a.stamina+=5;state.tea++;message='一杯奶茶的治愈：压力 −20，体力 +5。';}if(id==='old_bookstall'){if(Math.random()<.5){const k=Object.keys(subjects)[Math.floor(Math.random()*9)];a[k]+=5;state.inventory.push('绝版考题');message=`淘到绝版考题，${subjects[k]} +5。`;}else{a.stress-=35;state.inventory.push('闲书漫画');message='翻完一本漫画，压力 −35。（本地演示未模拟道德属性）';}}if(id==='part_time_job'){a.money+=80;a.stamina-=15;a.stress+=10;message='完成半天打工，零花钱 +80。';}log(message);commit(message);}
function story(){const e=events.filter(e=>e[1]<=state.week).at(-1);modal(`<span class="eyebrow">第 ${e[1]} 周 / 青春片段</span><h2 style="margin-top:15px">${e[0]}</h2><p>${e[2]}</p><p>${e[1]===1?'鞋底的热气、额头的汗水，还有站在身旁的新同学。你的高中生活，就这样开始了。':'有些时刻，回头看才发现，它已经成为青春的一部分。'}</p><p class="sub">${e[1]===1?'初次经历：体力 −10，压力 +10。':'此处为剧情目录展示；完整事件触发与选择仍需后端扩展。'}</p><button class="primary" style="margin-top:20px" data-remember="${e[1]}">${state.events.includes(e[1])?'合上这一页':'珍藏这一页'} →</button>`);}
function erf(x){const sign=x<0?-1:1;x=Math.abs(x);const t=1/(1+.3275911*x);return sign*(1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-x*x));}
function calculateExam(form){if(state.graduated)return;if(state.week!==156&&!canAct())return;const f=new FormData(form),a=state.attrs;let mod=f.get('essay')==='risky'?(Math.random()<.5?30:-20):10;if(f.get('math')==='force')mod+=a.math>100?25:-15;if(f.get('check')==='careful')mod+=5;else if(Math.random()<.15)mod-=40;const noise=Math.sqrt(-2*Math.log(Math.max(Number.EPSILON,Math.random())))*Math.cos(2*Math.PI*Math.random())*15;const score=Math.max(0,Math.min(750,Math.floor((a.chinese+a.math+a.english)*2.5+mod+noise)));const cdf=.5*(1+erf((score-450)/(80*Math.sqrt(2))));state.exam={score,rank:Math.max(1,Math.floor((1-cdf)*1000)),week:state.week};if(state.week===156){state.graduated=true;checkAchievements();state.legacy+=Math.floor(score/10)+state.earned.length*10+state.bonds.filter(x=>x===100).length*20;log('完成高考。'+ending());}else a.action_points--;log(`交上${state.graduated?'高考':'模拟考'}答卷，成绩 ${score} 分，年级第 ${state.exam.rank} 名。`);commit('答卷已经写好，这份成长属于你。');}
function ending(){const score=state.exam?.score||0;const level=score>=650?0:score>=580?1:score>=480?2:3;const max=Math.max(...state.bonds);const who=max>=60?state.bonds.indexOf(max):-1;const ends=[['兄弟双雄：一起撕碎命运的考卷','清北双璧：象牙塔顶峰相见','顶峰孤鹰：孤独的学霸传说'],['绿荫回忆：运动场上的余晖','沪上花开：平行时空的约定','平实学子：迈向未来的第一步'],['烟火人生：小镇啤酒与烧烤','异地相望：渐行渐远的青春','平凡之路：踏实也是一种答案'],['创业搭档：后街的摊位','遗憾错过：再见，班长','复读岁月：明年再战']];return ends[level][who===0?0:who===1?1:2];}
function letter(){modal(`<h2>${state.graduated?'毕业快乐，青禾同学。':'一封来自未来的信 · 预览'}</h2><p>${state.graduated?'属于你的高中三年，已经成为独一无二的纪念。':'这是本地逐字动画预览，不代表已完成毕业结算。'}</p><div class="letter" id="letter"></div>`);const text=`亲爱的青禾同学：\n\n三年的时光如白驹过隙，教学楼前蝉鸣的夏天仿佛还在昨日。\n还记得那些晚自习的灯光，和每一次没有放弃的你。\n${state.graduated?'高考 '+state.exam.score+' 分，是这段旅程的一页答卷。':'愿你在最后一场考试后，仍然记得最初的梦想。'}\n前路浩浩荡荡，万物皆可期待。\n\n毕业快乐，前程似锦！`;let i=0;clearInterval(letterTimer);letterTimer=setInterval(()=>{const el=$('#letter');if(!el||i>=text.length){clearInterval(letterTimer);return;}el.textContent+=text[i++];},35);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.go){location.hash=b.dataset.go;return;}if(b.dataset.subject){study(b.dataset.subject);return;}if(b.dataset.gift!==undefined){gift(Number(b.dataset.gift));return;}if(b.dataset.shop){shop(b.dataset.shop);return;}if(b.dataset.track){state.track=b.dataset.track;log('选择了'+(state.track==='science'?'理科':'文科')+'方向。');commit('未来的方向，由你来选。');return;}if(b.dataset.remember){const week=Number(b.dataset.remember);if(!state.events.includes(week)){state.events.push(week);if(week===1){state.attrs.stamina-=10;state.attrs.stress+=10;}log('珍藏故事：'+events.find(e=>e[1]===week)[0]);}closeModal();commit('这一页，已收进青春纪念册。');return;}const actions={study:chooseStudy,rest,next:nextWeek,'confirm-next':advance,event:story,letter,'confirm-legacy':startNewGame};actions[b.dataset.action]?.();});
let selectedPerks=[];
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='exam-form')calculateExam(e.target);if(e.target.id==='legacy-form'){selectedPerks=[...e.target.querySelectorAll('input:checked')].map(x=>x.value);const cost=selectedPerks.reduce((a,p)=>a+({'过目不忘':50,'家境优渥':40}[p]||0),0);if(cost>state.legacy)return toast('遗产点不足，试着少选一项天资。');modal(`<h2>开始一段新的青春？</h2><p>本周目的成绩、羁绊和纪念册将重置。保留剩余遗产点，携带所选天资进入第 ${state.round+1} 周目。</p><button class="primary" data-action="confirm-legacy">确定，翻开新的篇章 →</button>`);}});
document.addEventListener('change',e=>{if(e.target.name==='perk')$('#perk-total').textContent='已选天资合计：'+[...document.querySelectorAll('input[name="perk"]:checked')].reduce((a,p)=>a+Number(p.dataset.cost),0)+' 点';});
function startNewGame(){if(!state.graduated)return;const cost=selectedPerks.reduce((a,p)=>a+({'过目不忘':50,'家境优渥':40}[p]||0),0);const round=state.round+1,legacy=state.legacy-cost;state=initial();state.round=round;state.legacy=legacy;state.perks=selectedPerks;state.attrs.chinese=state.attrs.math=state.attrs.english=65;if(selectedPerks.includes('家境优渥'))state.attrs.money=300;closeModal();location.hash='home';commit('新的一页，仍然有无限可能。');}
$('#close-dialog').onclick=closeModal;$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))closeModal();});$('#dialog').addEventListener('cancel',()=>clearInterval(letterTimer));$('#save').onclick=()=>{persist();toast(storageOK?'这段时光，已经好好保存。':'浏览器禁止本地存储，暂时无法保存。');};$('#help').onclick=()=>modal('<h2>欢迎来到青禾高中。</h2><p>每周有 4 次行动，可以学习、休息、送礼或参加模拟考试。行动用完后，商业街开放；结束本周便进入下一周。</p><p>第 40 周起可以选择文理方向，第 156 周参加高考。毕业后用遗产点选择天资，开启新周目。</p><p>这是可离线运行的前端体验版，使用浏览器本地存档，尚未连接 FastAPI。基础数值参考附件后端；时间推进、休息和礼物价格为演示规则。契约剧情、部分成就与完整事件链尚未接入。</p>');
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});render();persist();
